### PR TITLE
crosstool-ng: Update to pull in fix for nano.spec

### LINKED ISSUE #369: Footprint increase
A significant footprint increase has been reported for the SDK 0.13.0-* releases.

For `samples/net/sockets/coap_client` with `nrf52840dk_nrf52840`

**0.12.4**
```
Memory region         Used Size  Region Size  %age Used
           FLASH:      116016 B         1 MB     11.06%
            SRAM:       28320 B       256 KB     10.80%
        IDT_LIST:          0 GB         2 KB      0.00%
```

**0.13.0-rc3**
```
Memory region         Used Size  Region Size  %age Used
           FLASH:      143080 B         1 MB     13.65%
            SRAM:       30336 B       256 KB     11.57%
        IDT_LIST:          0 GB         2 KB      0.00%
```

This increase happened after the commits in the PR #333, which switched to using the upstream crosstool-ng newlib nano build process.

### PR DESCRIPTION
**Pull request by galak**
pull in nano.spec fix that links with -lc_nano instead of -lc (same
for other nano lib variants, libm, libstdc++, etc..)

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

Fixes #369

### CODE REVIEW

File: go.sh [hunk 1]
```diff
@@ -176,7 +176,7 @@ for t in ${TARGETS}; do
 	rm -rf ${CT_PREFIX}/*/newlib-nano
```
Comment (stephanosio) [inline go.sh:176]: We should just set `CT_NEWLIB_NANO_INSTALL_IN_TARGET=n` and use the separate `newlib-nano` directory as done in Keith's original implementation. That seems to be a much cleaner approach IMO.

**Review by stephanosio — CHANGES_REQUESTED** [review]
This does fix the problem at hand, but I think we could probably do something else/arguably better.

See https://github.com/crosstool-ng/crosstool-ng/pull/1568#pullrequestreview-717613082

File: go.sh (hunk 1 above)
Comment (stephanosio) [reply go.sh:176]: This was evaluated in #379, but this does not seem feasible for the time being (see https://github.com/zephyrproject-rtos/sdk-ng/pull/379#issuecomment-889252433).

Reconsider switching to #379 in the future when the target library stripping patch is updated to handle stripping the libraries under the `newlib-nano` directory.

**Comment by stephanosio** [comment]
Confirmed working:
```
Memory region         Used Size  Region Size  %age Used
           FLASH:      116016 B         1 MB     11.06%
            SRAM:       28320 B       256 KB     10.80%
        IDT_LIST:          0 GB         2 KB      0.00%
```

**Review by stephanosio — APPROVED** [review]
